[green_agent]
agentbeats_id = "019ca155-47bc-7863-bbc5-4747c4c5975a"
env = { API_KEY = "${GITHUB_SECRET_NAME}", OPENAI_API_KEY = "${OPENAI_API_KEY}", LOG_LEVEL = "INFO" }

[[participants]]
agentbeats_id = ""
name = "agent"
env = {}

[config]
task_limit = 2140
drift_level = "none"
rot_level = "none"
org_type = "b2c"
max_steps = 7
timeout = 300
